### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by zhukeev** [huxq17/Pump#10]
D/Pump: huTest task video133.mp4 is ready,remaining 1 permits.
D/Pump: huTest start run task=video133.mp4
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
        at com.huxq17.download.message.MessageCenter$1.handleMessage(MessageCenter.java:35)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by huxq17** [comment]
What happened?

**Comment by zhukeev** [comment]
Had that error but when I update to 1.2.7 it's gone

**Comment by zhukeev** [comment]
> 
> 
> What happened?

It sometimes gives that error sometimes does not. I don't know why it's happening. I'm calling from callback maybe it's the cause. I've two Retrofit requests and inside of  **onResponse** I call Pump.newRequest(video.getUrl(), DIR_TO_VIDEOS + video.getFileName())
                    .forceReDownload(true)
                    .setRetry(3)
                    .threadNum(3)
I get list of Video from retrofit request so I download like that for every video with for loop

**Comment by huxq17** [comment]
Use v1.2.8 and problem is solved.
