### ISSUE TITLE
Change the path

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#22]
I have succeeded with moving the files after download finished using Okio and tree uri, but how to change the default path from downloadInfo? Thank you

**Comment by huxq17** [comment]
Why not change the path when you start download.

**Comment by nana-desu** [comment]
When trying to save to mounted storage ex "C821-4332", it doesn't work and gives "permission denied". So I need to use MediaStore or ACTION_OPEN_DOCUMENT_TREE method.

Btw I use SDK 29

**Comment by huxq17** [comment]
What's your full storage path?

**Comment by nana-desu** [comment]
/storage/0CE6-1D01/Test

``` 
W/System.err: java.io.IOException: Permission denied
W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
        at java.io.File.createNewFile(File.java:1008)
        at com.huxq17.download.core.task.SimpleDownloadTask.execute(SimpleDownloadTask.java:30)
        at com.huxq17.download.core.task.Task.run(Task.java:9)
        at com.huxq17.download.core.interceptor.DownloadFetchInterceptor.downloadWithoutBreakPoint(DownloadFetchInterceptor.java:45)
        at com.huxq17.download.core.interceptor.DownloadFetchInterceptor.intercept(DownloadFetchInterceptor.java:31)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.interceptor.CheckCacheInterceptor.parseResponse(CheckCacheInterceptor.java:116)
        at com.huxq17.download.core.interceptor.CheckCacheInterceptor.intercept(CheckCacheInterceptor.java:70)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:102)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:88)
        at com.huxq17.download.core.task.Task.run(Task.java:9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
```

**Comment by huxq17** [comment]
Use v1.2.14,and DownloadInfo#updateFilePath will change the path, see changePathInterceptor in  [DemoApplication](https://github.com/huxq17/Pump/blob/master/app/src/main/java/com/huxq17/download/demo/DemoApplication.java) for details.
