### ISSUE TITLE
Can't start the download list activity

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#27]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.usamin., PID: 24650
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.usamin./com.usamin..activity.drawer.DownloadsActivity2}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at com.huxq17.download.android.ViewLifecycleHandler$ViewHandlerManager.handleLifecycleForActivity(ViewLifecycleHandler.java:37)
        at com.huxq17.download.android.ViewLifecycleHandler$ViewHandlerManager.access$100(ViewLifecycleHandler.java:25)
        at com.huxq17.download.android.ViewLifecycleHandler.handleLifecycleForActivity(ViewLifecycleHandler.java:18)
        at com.huxq17.download.core.DownloadListener.<init>(DownloadListener.java:19)
        at com.usamin..activity.drawer.DownloadsActivity2$downloadListener$1.<init>(DownloadsActivity2.kt:26)
        at com.usamin..activity.drawer.DownloadsActivity2.<init>(DownloadsActivity2.kt:26)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by huxq17** [comment]
Create downloadListener in activity's constructor?

**Comment by nana-desu** [comment]
your demo also doesn't work
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huxq17.download.demo, PID: 2791
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.huxq17.download.demo/com.huxq17.download.demo.DownloadListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)

```

SDK 29

**Comment by huxq17** [comment]
My fault,activity.getApplication is null at instantiate, you can remove activity from constructor to avoid error

**Comment by nana-desu** [comment]
Still same, i remove the start constructor and tag.

``` 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huxq17.download.demo, PID: 5033
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.huxq17.download.demo/com.huxq17.download.demo.DownloadListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2548)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at com.huxq17.download.android.ViewLifecycleHandler$ViewHandlerManager.handleLifecycleForActivity(ViewLifecycleHandler.java:37)
        at com.huxq17.download.android.ViewLifecycleHandler$ViewHandlerManager.access$100(ViewLifecycleHandler.java:25)
        at com.huxq17.download.android.ViewLifecycleHandler.handleLifecycleForActivity(ViewLifecycleHandler.java:18)
        at com.huxq17.download.core.DownloadListener.<init>(DownloadListener.java:19)
        at com.huxq17.download.demo.DownloadListActivity$1.<init>(DownloadListActivity.java:33)
        at com.huxq17.download.demo.DownloadListActivity.<init>(DownloadListActivity.java:33)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2538)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**Comment by nana-desu** [comment]
```

public class DownloadListActivity extends AppCompatActivity {


    DownloadListener downloadListener = new DownloadListener(this) {
        @Override
        public void onProgress(int progress) {
            DownloadInfo downloadInfo = getDownloadInfo();
            DownloadViewHolder viewHolder = (DownloadViewHolder) downloadInfo.getExtraData();
            if (viewHolder != null) {
                DownloadInfo tag = map.get(viewHolder);
                if (tag != null && tag.getId().equals(downloadInfo.getId())) {
                    viewHolder.bindData(downloadInfo);
                }
            }
        }

        @Override
        public void onFailed() {
            super.onFailed();
            LogUtil.e("onFailed code=" + getDownloadInfo().getErrorCode());
        }
    };
    private HashMap<DownloadViewHolder, DownloadInfo> map = new HashMap<>();
    private RecyclerView recyclerView;
    private DownloadAdapter downloadAdapter;
    private List<DownloadInfo> downloadInfoList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_download_list);
        downloadListener.enable();
        recyclerView = findViewById(R.id.rvDownloadList);
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
        //Get all download list.
        downloadInfoList = Pump.getAllDownloadList()

        //Sort download list if need.
        Collections.sort(downloadInfoList, new Comparator<DownloadInfo>() {
            @Override
            public int compare(DownloadInfo o1, DownloadInfo o2) {
                return (int) (o1.getCreateTime() - o2.getCreateTime());
            }
        });
        recyclerView.setLayoutManager(linearLayoutManager);
        downloadAdapter = new DownloadAdapter(map, downloadInfoList);
        recyclerView.setAdapter(downloadAdapter);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        for (DownloadInfo downloadInfo : downloadInfoList) {
            Pump.stop(downloadInfo.getId());
        }
        Pump.shutdown();
    }

    public static class DownloadAdapter extends RecyclerView.Adapter<DownloadViewHolder> {
        List<DownloadInfo> downloadInfoList;
        HashMap<DownloadViewHolder, DownloadInfo> map;

        public DownloadAdapter(HashMap<DownloadViewHolder, DownloadInfo> map, List<DownloadInfo> downloadInfoList) {
            this.downloadInfoList = downloadInfoList;
            this.map = map;
        }

        @NonNull
        @Override
        public DownloadViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
            View v = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.item_download_list, viewGroup, false);
            return new DownloadViewHolder(v, this);
        }

        @Override
        public void onBindViewHolder(@NonNull DownloadViewHolder viewHolder, int i) {
            DownloadInfo downloadInfo = downloadInfoList.get(i);
            downloadInfo.setExtraData(viewHolder);
            map.put(viewHolder, downloadInfo);

            viewHolder.bindData(downloadInfo);
        }

        public void delete(DownloadViewHolder viewHolder) {
            int position = viewHolder.getAdapterPosition();
            downloadInfoList.remove(position);
            notifyItemRemoved(position);
            map.remove(viewHolder);
        }

        @Override
        public int getItemCount() {
            return downloadInfoList.size();
        }
    }

    public static class DownloadViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener, View.OnLongClickListener {
        ProgressBar progressBar;
        TextView tvName;
        TextView tvStatus;
        TextView tvSpeed;
        TextView tvDownload;
        DownloadInfo downloadInfo;
        DownloadInfo.Status status;
        AlertDialog dialog;

        public DownloadViewHolder(@NonNull View itemView, final DownloadAdapter adapter) {
            super(itemView);
            progressBar = itemView.findViewById(R.id.pb_progress);
            tvName = itemView.findViewById(R.id.tv_name);
            tvStatus = itemView.findViewById(R.id.bt_status);
            tvSpeed = itemView.findViewById(R.id.tv_speed);
            tvDownload = itemView.findViewById(R.id.tv_download);
            tvStatus.setOnClickListener(this);
            itemView.setOnLongClickListener(this);
            dialog = new AlertDialog.Builder(itemView.getContext())
                    .setTitle("Confirm delete?")
                    .setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                            adapter.delete(DownloadViewHolder.this);
                            Pump.deleteById(downloadInfo.getId());
                        }
                    })
                    .setNegativeButton("No", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {

                        }
                    })
                    .create();
        }

        public void bindData(DownloadInfo downloadInfo) {
            this.downloadInfo = downloadInfo;
            this.status = downloadInfo.getStatus();
            tvName.setText(downloadInfo.getName());
            String speed = "";
            int progress = downloadInfo.getProgress();
            progressBar.setProgress(progress);
            switch (status) {
                case STOPPED:
                    tvStatus.setText("Start");
                    break;
                case PAUSING:
                    tvStatus.setText("Pausing");
                    break;
                case PAUSED:
                    tvStatus.setText("Continue");
                    break;
                case WAIT:
                    tvStatus.setText("Waiting");
                    break;
                case RUNNING:
                    tvStatus.setText("Pause");
                    speed = downloadInfo.getSpeed();
                    break;
                case FINISHED:
                    tvStatus.setText("Install");
                    break;
                case FAILED:
                    tvStatus.setText("Retry");
                    break;
            }
            tvSpeed.setText(speed);
            long completedSize = downloadInfo.getCompletedSize();
            long totalSize = downloadInfo.getContentLength();
            tvDownload.setText(Utils.getDataSize(completedSize) + "/" + Utils.getDataSize(totalSize));
        }

        @Override
        public void onClick(View v) {
            if (v == tvStatus) {
                switch (status) {
                    case STOPPED:
                    case PAUSED:
                    case FAILED:
                        Pump.resume(downloadInfo.getId());
                        break;
                    case WAIT:
                        //do nothing.
                        break;
                    case RUNNING:
                        Pump.pause(downloadInfo.getId());
                        break;
                    case FINISHED:
                        APK.with(itemView.getContext())
                                .from(downloadInfo.getFilePath())
                                .install();
                        break;
                }
            }

        }

        @Override
        public boolean onLongClick(View v) {
            dialog.show();
            return true;
        }
    }

}

```

**Comment by huxq17** [comment]
Remove activity from downloadListener's  constructor.

**Comment by huxq17** [comment]
I fixed this error in DownloadListActivity

**Comment by nana-desu** [comment]
ok.. fixed, thank you

**Comment by nana-desu** [comment]
sometimes download crashes with zippyshare
```
  val downloadInfo = downloadInfo
      val viewHolder = downloadInfo.extraData as DownloadViewHolder
      val tag = map[viewHolder]
      if (tag != null && tag.id == downloadInfo.id) {
        viewHolder.bindData(downloadInfo)
      }
```

```
E/ACRA: ACRA caught a TypeCastException for com.usamin
    kotlin.TypeCastException: null cannot be cast to non-null type com.usamin.activity.drawer.DownloadsActivity2.DownloadViewHolder
        at com.usamin.activity.drawer.DownloadsActivity2$downloadListener$1.onProgress(DownloadsActivity2.kt:26)
        at com.huxq17.download.core.DownloadListener.downloading(DownloadListener.java:58)
        at com.huxq17.download.core.MessageCenter.handleDownloadInfoSnapshot(MessageCenter.java:42)
        at com.huxq17.download.core.MessageCenter$1.handleMessage(MessageCenter.java:24)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

```
   Pump.newRequest(url).threadNum(8).disableBreakPointDownload()
      .forceReDownload(true).setRetry(15, 200).submit()
```

**Comment by huxq17** [comment]
It looks like downloadInfo.extraData is null,maybe you should check non-null first.

**Comment by nana-desu** [comment]
Please push the latest version, thank you. I use 1.3.1 but can't implement Request.Builder type as documented
![image](https://user-images.githubusercontent.com/59090734/83263284-8be8dd00-a1e8-11ea-840b-0ab8392c8e84.png)

**Comment by huxq17** [comment]
Use v1.3.2.
