### ISSUE TITLE
Too many follow-up requests: 21

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#28]
Is there any fix with this kind of error? I saw many answers on SO had an issue with API or too many redirections.
Can you test download file from dood.to?

Thank you

```
W/System.err: java.net.ProtocolException: Too many follow-up requests: 21
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:121)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.androidnetworking.interceptors.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:154)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
W/System.err:     at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:51)
        at com.huxq17.download.core.interceptor.CheckCacheInterceptor.intercept(CheckCacheInterceptor.java:56)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)```

**Comment by nana-desu** [comment]
![image](https://user-images.githubusercontent.com/59090734/83354752-ea4ac280-a384-11ea-9110-4fb42cc865fc.png)
![image](https://user-images.githubusercontent.com/59090734/83354833-87a5f680-a385-11ea-872d-c7c6980b83b6.png)

but it works with default android download manager

**Comment by nana-desu** [comment]
always get socket closed when downloading from racaty.net

```
W/System.err: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at okio.InputStreamSource.read(Okio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:207)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
W/System.err:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
        at com.huxq17.download.core.task.DownloadBlockTask.execute(DownloadBlockTask.java:60)
        at com.huxq17.download.core.task.Task.run(Task.java:9)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by huxq17** [comment]
I will resolve it at this week.

**Comment by nana-desu** [comment]
For https://github.com/huxq17/Pump/commit/4829230dc3ae6e99319f11bf2dd5b759e1e5f5cc

i keep getting this error message
E/Pump: Pump onFailed code=ERROR_CONTENT_LENGTH_NOT_FOUND

**Comment by huxq17** [comment]
This code is not published,the error maybe caused by chunked transfer encoding,I have fixed it at local code.

**Comment by nana-desu** [comment]
Download is very slow, i think it is related to OkHttp. I tried many download manager on github with OkHttp and i have similar issuses with download stabilty. sometimes stuck at start, no network, slow download, ssl issue, failed to download.


OkHttp 4.7.2

**Comment by nana-desu** [comment]
Can you fix the database.. sometimes download list got duplicated and deleted files reappearing again

**Comment by huxq17** [comment]
Any more infomation about this mistake?

> Can you fix the database.. sometimes download list duplicated and deleted files reappearing again

**Comment by nana-desu** [comment]
i copied DownloadListActivity.java and convert them to kotlin... But in the previous build (i forgot what ver..), download list worked fine with no duplicated data.

Sometimes when starting download from the browser and go back to download list, files duplicated. Also when i try to delete, files reappear again as DownloadInfo.DELETED

**Comment by huxq17** [comment]
After I review the code, I find this behavior is unblieveble,could you provide a demo for this situation?

**Comment by huxq17** [comment]
> Can you fix the database.. sometimes download list duplicated and deleted files reappearing again

Use v1.3.4 and remove Pump.shutdown method maybe fix this problem.
