### ISSUE TITLE
Crash when download start after update to 1.3.4 and later

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#30]
```
E/AndroidRuntime: FATAL EXCEPTION: pool-22-thread-3
    java.lang.NullPointerException: Attempt to invoke interface method 'void okio.BufferedSink.flush()' on a null object reference
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.flushDownload(OkHttpDownloadConnection.java:71)
        at com.huxq17.download.core.task.DownloadBlockTask.execute(DownloadBlockTask.java:102)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by huxq17** [comment]
Fixed in v1.3.6.
