### ISSUE TITLE
Downloaded file corrupted or not finished yet

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#31]
<img src="https://user-images.githubusercontent.com/59090734/87751094-732f9780-c827-11ea-8797-7a8ec8a3599e.gif" width="200px"> <img src="https://user-images.githubusercontent.com/59090734/87751948-6b70f280-c829-11ea-8d96-b9cad4cf1051.png" width="200px">

```
1st try
E/Pump: Pump onFailed code=ERROR_NETWORK_UNAVAILABLE
2nd try
D/Pump: Pump Merge 100MB_1.zip spend=0; file.length=188977
D/Pump: Pump download 100MB_1.zip is stopped, and spend=772 <<
```

https://www20.zippyshare.com/v/mgb8cJ2B/file.html

Please fix this, thank you

**Comment by huxq17** [comment]
![image](https://user-images.githubusercontent.com/11348713/87760719-c06d3280-c842-11ea-834d-2dc5658da505.png)
![image](https://user-images.githubusercontent.com/11348713/87760742-cbc05e00-c842-11ea-84b0-a5eefbbc5a49.png)
but I can download successful, is your network error?

**Comment by nana-desu** [comment]
Can you test this url
- https://racaty.net/mwkig2kazdxo
- https://gofile.io/d/M0bg1X
- https://userscloud.com/6g60u2gz17rr

Download always failed 
Thank you

**Comment by nana-desu** [comment]
I tested on other devices, still same.
Download failed at 130kb

**Comment by nana-desu** [comment]
> ![image](https://user-images.githubusercontent.com/11348713/87760719-c06d3280-c842-11ea-834d-2dc5658da505.png)
> ![image](https://user-images.githubusercontent.com/11348713/87760742-cbc05e00-c842-11ea-84b0-a5eefbbc5a49.png)
> I can download success by WebViewDownloadActivity, is your network error?

this happened also on the real device
![image](https://user-images.githubusercontent.com/59090734/88368542-84911a80-cdb8-11ea-8395-1c21fdf072de.png)

**Comment by nana-desu** [comment]
ok, fixed by adding disableBreakpoint

**Comment by huxq17** [comment]
download with only one threadnum maybe can also fix this, disableBreakpoint is not recommended.

**Comment by nana-desu** [comment]
I set the thread to 1 and works
The other problem is, I noticed some of other users sometimes getting stuck while downloading, this happened also with me any time.
When it get stuck Pump.stop() not functioning, and need to wait for a while, maybe when setRetry done

from me
![image](https://user-images.githubusercontent.com/59090734/88491556-b9c28600-cfcd-11ea-888b-643009568121.png)

other user
![image](https://user-images.githubusercontent.com/59090734/88491544-a57e8900-cfcd-11ea-99b4-f0dd748d848e.png)


``` 
W/System.err: java.net.SocketTimeoutException: Read timed out
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
W/System.err:     at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.connect(ConnectInterceptor.java:243)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:72)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
V/FA: Inactivity, disconnecting from the service
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:331)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:368)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:267)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.downloadBuffer(OkHttpDownloadConnection.java:62)
W/System.err:     at com.huxq17.download.core.task.DownloadBlockTask.download(DownloadBlockTask.java:138)
        at com.huxq17.download.core.task.DownloadBlockTask.execute(DownloadBlockTask.java:99)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:148)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    Caused by: java.net.SocketException: socket is closed
W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
    	... 20 more
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
W/System.err:     at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
W/System.err:     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
W/System.err:     at com.huxq17.download.core.interceptor.ConnectInterceptor.connect(ConnectInterceptor.java:243)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:72)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
W/System.err:     at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
W/System.err:     at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
W/System.err: Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
    	... 30 more
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
W/System.err:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.connect(ConnectInterceptor.java:243)
W/System.err:     at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:72)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
W/System.err:     at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/System.err: Caused by: java.net.SocketTimeoutException: Read timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/System.err:     at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
    	... 30 more
```
