### ISSUE TITLE
SQLiteException: table download_info_temp has 8 columns but 7 values were

### ISSUE THREAD

**Issue by AndreyFetisov** [huxq17/Pump#33]
Hello, what could be the reason for this error?

Fatal Exception: android.database.sqlite.SQLiteException: table download_info_temp has 8 columns but 7 values were supplied (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO download_info_temp SELECT * FROM download_info;
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1372)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:811)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2321)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
       at com.huxq17.download.db.DBOpenHelper.newVersion4(DBOpenHelper.java:69)
       at com.huxq17.download.db.DBOpenHelper.newVersion5(DBOpenHelper.java:89)
       at com.huxq17.download.db.DBOpenHelper.onUpgrade(DBOpenHelper.java:132)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
       at com.huxq17.download.db.DBService.getDatabase(DBService.java:132)
       at com.huxq17.download.db.DBService.getDownloadInfo(DBService.java:112)
       at com.huxq17.download.core.DownloadDispatcher.createDownloadInfo(DownloadDispatcher.java:201)
       at com.huxq17.download.core.DownloadDispatcher.createTaskFromRequest(DownloadDispatcher.java:161)
       at com.huxq17.download.core.DownloadDispatcher.consumeRequest(DownloadDispatcher.java:72)
       at com.huxq17.download.core.DownloadDispatcher.execute(DownloadDispatcher.java:93)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by huxq17** [comment]
Fixed in v1.3.7.

**Comment by AndreyFetisov** [comment]
Thanks!

**Comment by AndreyFetisov** [comment]
Please fix typo "CHAR **efault**('')"

**Comment by huxq17** [comment]
ok,but sqlite upgrade is work fine now.

**Comment by AndreyFetisov** [comment]
Thanks!

**Comment by AndreyFetisov** [comment]
hI,

this issue persists in version 1.3.7.

Fatal Exception: android.database.sqlite.SQLiteException: table download_info_temp has 8 columns but 7 values were supplied (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO download_info_temp SELECT * FROM download_info;
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1372)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:811)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2321)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
       at com.huxq17.download.db.DBOpenHelper.newVersion4(DBOpenHelper.java:73)
       at com.huxq17.download.db.DBOpenHelper.newVersion5(DBOpenHelper.java:93)
       at com.huxq17.download.db.DBOpenHelper.onUpgrade(DBOpenHelper.java:136)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
       at com.huxq17.download.db.DBService.getDatabase(DBService.java:132)
       at com.huxq17.download.db.DBService.getDownloadInfo(DBService.java:112)
       at com.huxq17.download.core.DownloadDispatcher.createDownloadInfo(DownloadDispatcher.java:201)
       at com.huxq17.download.core.DownloadDispatcher.createTaskFromRequest(DownloadDispatcher.java:161)
       at com.huxq17.download.core.DownloadDispatcher.consumeRequest(DownloadDispatcher.java:72)
       at com.huxq17.download.core.DownloadDispatcher.execute(DownloadDispatcher.java:93)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
