### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException: table download_info_temp has 8 columns but 7 values were supplied (code 1):

### ISSUE THREAD

**Issue by AndreyFetisov** [huxq17/Pump#35]
Fatal Exception: android.database.sqlite.SQLiteException: table download_info_temp has 8 columns but 7 values were supplied (code 1): , while compiling: INSERT INTO download_info_temp SELECT * FROM download_info;
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(table download_info_temp has 8 columns but 7 values were supplied (code 1): , while compiling: INSERT INTO download_info_temp SELECT * FROM download_info;)
#################################################################
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1006)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:571)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1838)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1769)
       at com.huxq17.download.db.DBOpenHelper.newVersion4(DBOpenHelper.java:73)
       at com.huxq17.download.db.DBOpenHelper.newVersion5(DBOpenHelper.java:93)
       at com.huxq17.download.db.DBOpenHelper.onUpgrade(DBOpenHelper.java:136)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.huxq17.download.db.DBService.getDatabase(DBService.java:132)
       at com.huxq17.download.db.DBService.getDownloadInfo(DBService.java:112)
       at com.huxq17.download.core.DownloadDispatcher.createDownloadInfo(DownloadDispatcher.java:201)
       at com.huxq17.download.core.DownloadDispatcher.createTaskFromRequest(DownloadDispatcher.java:161)
       at com.huxq17.download.core.DownloadDispatcher.consumeRequest(DownloadDispatcher.java:72)
       at com.huxq17.download.core.DownloadDispatcher.execute(DownloadDispatcher.java:93)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by huxq17** [comment]
I have found the reason, will resolved at next version.

**Comment by AndreyFetisov** [comment]
Thanks!

**Comment by huxq17** [comment]
use v1.3.8.
