### ISSUE TITLE
getDownloadInfo()' on a null object reference

### ISSUE THREAD

**Issue by AndreyFetisov** [huxq17/Pump#36]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.huxq17.download.core.DownloadDetailsInfo com.huxq17.download.core.task.DownloadTask.getDownloadInfo()' on a null object reference
       at com.huxq17.download.utils.Util.setFilePathIfNeed(Util.java:253)
       at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:80)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
       at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
       at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

**Comment by huxq17** [comment]
Have you download at different thread?

**Comment by AndreyFetisov** [comment]
I have an Activity with Download Button. When user clicked this button I fired "Pump.newRequest(secUrl, filePath)". Perhaps the user closes the Activity and opens it again.

**Comment by huxq17** [comment]
Have you do sth when activity finished?

**Comment by AndreyFetisov** [comment]
No, 

i have only this code:

@Override
    protected void onResume() {
        super.onResume();

        downloadObserver.enable();
 }

 @Override
    protected void onPause() {
        super.onPause();

        downloadObserver.disable();
    }

 private void enqueueDownload(String filePath) {

 Pump.newRequest(secUrl, filePath)
                .forceReDownload(true)
                .threadNum(2)
                .setId(file.Id)
                .tag(file.Name)
                .listener(downloadObserver)
                .setRetry(3, 200)
                .submit();
 }

private void stopDownload(){

 Pump.stop(downloadObserver.getId());

}

**Comment by phxnirvana** [comment]
Maybe the reason is some code with db mixed id and url.

Since I overwrite the library with kotlin so I cannot commit my changes directly.

> Have you download at different thread? I need more info to location exception.

**Comment by huxq17** [comment]
Another issues about sql exception is db code mistake,Ihave fixed it at local. but I dont know their relationship.

**Comment by AndreyFetisov** [comment]
Maybe I should try to simplify the configuration as much as possible? Remove additional parameters from a function Pump.newRequest

**Comment by huxq17** [comment]
> Maybe I should try to simplify the configuration as much as possible? Remove additional parameters from a function Pump.newRequest

Dont need to do this.

**Comment by huxq17** [comment]
I had release version 1.3.8, you can use this to verify this problem is exist or not.

**Comment by AndreyFetisov** [comment]
many thanks!

**Comment by AndreyFetisov** [comment]
Thanks a lot!

**Comment by huxq17** [comment]
I have been able to reproduce this problem stably, and fixed this issues at version 1.3.9

**Comment by AndreyFetisov** [comment]
Thanks!
