### ISSUE TITLE
Download stuck

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#37]
I noticed some of other users sometimes getting stuck while downloading, this happened also with me any time.
When it getting stuck Pump.stop() not functioning, and need to wait for a while, maybe when setRetry task done

https://gofile.io/d/M0bg1X

from me
![image](https://user-images.githubusercontent.com/59090734/88491556-b9c28600-cfcd-11ea-888b-643009568121.png)

other user
![image](https://user-images.githubusercontent.com/59090734/88491544-a57e8900-cfcd-11ea-99b4-f0dd748d848e.png)

``` 
W/System.err: java.net.SocketTimeoutException: Read timed out
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
W/System.err:     at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.connect(ConnectInterceptor.java:243)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:72)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
V/FA: Inactivity, disconnecting from the service
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:331)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:368)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:267)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.downloadBuffer(OkHttpDownloadConnection.java:62)
W/System.err:     at com.huxq17.download.core.task.DownloadBlockTask.download(DownloadBlockTask.java:138)
        at com.huxq17.download.core.task.DownloadBlockTask.execute(DownloadBlockTask.java:99)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:148)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    Caused by: java.net.SocketException: socket is closed
W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
    	... 20 more
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
W/System.err:     at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
W/System.err:     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
W/System.err:     at com.huxq17.download.core.interceptor.ConnectInterceptor.connect(ConnectInterceptor.java:243)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:72)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
W/System.err:     at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
W/System.err:     at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
W/System.err: Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
    	... 30 more
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
W/System.err:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.huxq17.download.core.connection.OkHttpDownloadConnection.connect(OkHttpDownloadConnection.java:44)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.connect(ConnectInterceptor.java:243)
W/System.err:     at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:72)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
W/System.err:     at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
W/System.err:     at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/System.err: Caused by: java.net.SocketTimeoutException: Read timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/System.err:     at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
    	... 30 more
```

**Comment by huxq17** [comment]
what do you want? setRetry maybe a functional way. Pump.stop() can not interrupt download while network is stuck.

**Comment by nana-desu** [comment]
Some of my users said they don't have any issue with download while using chrome, other browsers, or maybe download manager.

**Comment by huxq17** [comment]
It looks like Okhttp's bug.

**Comment by huxq17** [comment]
But system's download manager using HttpUrlConnection, it's implemetation is Okhttp .

**Comment by nana-desu** [comment]
Okhttp download failed at 20%

<img src="https://user-images.githubusercontent.com/59090734/88554547-d81d9580-d050-11ea-9b54-1879a2da8ae9.jpg" width="200">

Httpurlconnection still continue until done

<img src="https://user-images.githubusercontent.com/59090734/88554542-d6ec6880-d050-11ea-8802-4e05871ed03f.jpg" width="200"> <img src="https://user-images.githubusercontent.com/59090734/88555087-8590a900-d051-11ea-9e89-9c4f55174d5d.jpg" width="200">

**Comment by nana-desu** [comment]
This also happened with dood.to and ddl.to or maybe with other some file hosting. Download always failed at start but with HttpUrlConnection I can download without issue

**Comment by huxq17** [comment]
I will test later.

**Comment by huxq17** [comment]
Have you download with multi thread,android system downloader is download with single thread.

**Comment by nana-desu** [comment]
It works by set the thread to 1, but for download failed at start it doesn't.

Can you test dood.to?

**Comment by huxq17** [comment]
> It works by set the thread to 1, but for download failed at start it doesn't.
> 
> Can you test dood.to?

timeout is fixed by set thread num to 1？what is dowload failed at start?

**Comment by nana-desu** [comment]
I set threadNum to 1
![Screenshot_20200730-061924782.jpg](https://user-images.githubusercontent.com/59090734/88863302-b0832480-d22c-11ea-86d7-8242ab41ed38.jpg)

It is fixed now
