### ISSUE TITLE
UNIQUE constraint failed: download_info_temp.id (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)

### ISSUE THREAD

**Issue by AndreyFetisov** [huxq17/Pump#38]
Hi, new error at 1.3.9

Fatal Exception: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: download_info_temp.id (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 2:No such file or directory)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:877)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:776)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1899)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1816)
       at com.huxq17.download.db.DBOpenHelper.newVersion4(DBOpenHelper.java:72)
       at com.huxq17.download.db.DBOpenHelper.newVersion5(DBOpenHelper.java:92)
       at com.huxq17.download.db.DBOpenHelper.onUpgrade(DBOpenHelper.java:135)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:436)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:332)
       at com.huxq17.download.db.DBService.getDatabase(DBService.java:132)
       at com.huxq17.download.db.DBService.getDownloadInfo(DBService.java:112)
       at com.huxq17.download.core.DownloadDispatcher.createDownloadInfo(DownloadDispatcher.java:202)
       at com.huxq17.download.core.DownloadDispatcher.createTaskFromRequest(DownloadDispatcher.java:162)
       at com.huxq17.download.core.DownloadDispatcher.consumeRequest(DownloadDispatcher.java:73)
       at com.huxq17.download.core.DownloadDispatcher.execute(DownloadDispatcher.java:94)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

**Comment by huxq17** [comment]
it's fixed at v1.3.10.
