### ISSUE TITLE
E/SQLiteLog: (1) table download_info has no column named schema_uri

### ISSUE THREAD

**Issue by Equin** [huxq17/Pump#43]
hello , i have this error whyle trying to download url=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia.
i have such exception. On android 9 same code works without this exception.

2021-04-12 16:27:36.825 14323-14323/com.example.app V/AsyncHttpRH: Progress 9953 from 1 (995300%)
2021-04-12 16:27:38.329 14323-14669/com.example.app E/SQLiteLog: (1) table download_info has no column named schema_uri in "INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)"
2021-04-12 16:27:38.329 14323-14669/com.example.app E/SQLiteDatabase: Error inserting thread_num=0 finished=0 create_time=1618234058325 schema_uri=null id=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia tag=music url=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia path=null file_length=-1
    android.database.sqlite.SQLiteException: table download_info has no column named schema_uri (code 1 SQLITE_ERROR): , while compiling: INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1699)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1617)
        at com.huxq17.download.db.DBService.updateInfo(DBService.java:78)
        at com.huxq17.download.core.DownloadDispatcher.createDownloadInfo(DownloadDispatcher.java:185)
        at com.huxq17.download.core.DownloadDispatcher.createTaskFromRequest(DownloadDispatcher.java:150)
        at com.huxq17.download.core.DownloadDispatcher.consumeRequest(DownloadDispatcher.java:65)
        at com.huxq17.download.core.DownloadDispatcher.run(DownloadDispatcher.java:86)
2021-04-12 16:27:38.330 14323-14669/com.example.app D/Pump: Pump Task http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia is ready.
2021-04-12 16:27:38.332 14323-15612/com.example.app D/Pump: Pump start run http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia at thread name=MusicDownloadDispatcher-thread-4
2021-04-12 16:27:38.338 561-2074/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2021-04-12 16:27:38.472 561-2074/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2021-04-12 16:27:39.561 14323-15612/com.example.app E/SQLiteLog: (1) table download_info has no column named schema_uri in "INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)"
2021-04-12 16:27:39.562 14323-15612/com.example.app E/SQLiteDatabase: Error inserting thread_num=0 finished=0 create_time=1618234058325 schema_uri=null id=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia tag=music url=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia path=/storage/emulated/0/Android/data/com.example.app/files/pump_cache/com.zhiyoo_43951200_0.apk file_length=-1
    android.database.sqlite.SQLiteException: table download_info has no column named schema_uri (code 1 SQLITE_ERROR): , while compiling: INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1699)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1617)
        at com.huxq17.download.db.DBService.updateInfo(DBService.java:78)
        at com.huxq17.download.core.task.DownloadTask.updateInfo(DownloadTask.java:167)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.prepareDownloadFile(ConnectInterceptor.java:301)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:83)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:98)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:84)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-04-12 16:27:39.579 14323-15612/com.example.app E/SQLiteLog: (1) table download_info has no column named schema_uri in "INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)"
2021-04-12 16:27:39.579 14323-15612/com.example.app E/SQLiteDatabase: Error inserting thread_num=2 finished=0 create_time=1618234058325 schema_uri=null id=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia tag=music url=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia path=/storage/emulated/0/Android/data/com.example.app/files/pump_cache/com.zhiyoo_43951200_0.apk file_length=2957323
    android.database.sqlite.SQLiteException: table download_info has no column named schema_uri (code 1 SQLITE_ERROR): , while compiling: INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1699)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1617)
        at com.huxq17.download.db.DBService.updateInfo(DBService.java:78)
        at com.huxq17.download.core.task.DownloadTask.updateInfo(DownloadTask.java:167)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.checkDownloadFile(ConnectInterceptor.java:199)
        at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:137)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
        at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:98)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:84)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-04-12 16:27:40.505 1287-1401/? I/PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
2021-04-12 16:27:40.505 1287-1401/? I/PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
2021-04-12 16:27:41.428 561-2074/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2021-04-12 16:27:41.576 14323-15567/com.example.app V/FA: Inactivity, disconnecting from the service
2021-04-12 16:27:41.703 1287-1401/? I/PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
2021-04-12 16:27:41.704 1287-1401/? I/PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
2021-04-12 16:27:42.375 14323-15612/com.example.app D/Pump: Pump Merge com.zhiyoo_43951200_0.apk spend=11; file.length=2957323
2021-04-12 16:27:42.379 14323-15612/com.example.app E/SQLiteLog: (1) table download_info has no column named schema_uri in "INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)"
2021-04-12 16:27:42.379 14323-15612/com.example.app E/SQLiteDatabase: Error inserting thread_num=2 finished=1 create_time=1618234058325 schema_uri=null id=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia tag=music url=http://wdj.anzhi.com/dl_app.php?s=2397021&channel=wandoujia path=/storage/emulated/0/Android/data/com.example.app/files/pump_cache/com.zhiyoo_43951200_0.apk file_length=2957323
    android.database.sqlite.SQLiteException: table download_info has no column named schema_uri (code 1 SQLITE_ERROR): , while compiling: INSERT OR REPLACE  INTO download_info(thread_num,finished,create_time,schema_uri,id,tag,url,path,file_length) VALUES (?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1699)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1617)
        at com.huxq17.download.db.DBService.updateInfo(DBService.java:78)
        at com.huxq17.download.core.task.DownloadTask.updateInfo(DownloadTask.java:167)
        at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:104)
        at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:84)
        at com.huxq17.download.core.task.Task.run(Task.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-04-12 16:27:42.380 14323-15612/com.example.app D/Pump: Pump download com.zhiyoo_43951200_0.apk is stopped,and spend=4048

**Comment by huxq17** [comment]
What's the matter? Sorry about later reply, I was  busy this week.
